(() => {
  "use strict";
  const STICKY_HEADER_OFFSET = 130;
  const $ = (s,r=document)=>r.querySelector(s);
  const $$ = (s,r=document)=>[...r.querySelectorAll(s)];
  const state = {section:0,equipment:[],ids:[],measure:null,ox:null,inspection:[],breath:null,interpret:null,doc:null};

  const equipment = [
    ["stethoscope","Stethoscope","assets/stethoscope.png",true],
    ["pulse-ox","Pulse oximeter","assets/pulse-oximeter-probe.png",true],
    ["timer","Watch / timer","assets/watch-timer.png",true],
    ["clipboard","Clipboard / documentation","assets/clipboard.png",true],
    ["nebulizer","Nebulizer kit","assets/nebulizer-kit.png",false],
    ["abg","ABG syringe","assets/abg-syringe.png",false],
    ["suction","Suction catheter","assets/suction-catheter.png",false],
    ["spirometer","Incentive spirometer","assets/incentive-spirometer.png",false]
  ];
  const connectExpected=["Perform hand hygiene","Introduce yourself and explain the respiratory assessment","Verify two patient identifiers","Position the patient upright as tolerated"];
  const closeExpected=["Return the patient to a safe, comfortable position","Clean or return equipment according to facility practice","Perform hand hygiene","Document the assessment","Report or escalate clinically significant findings if present"];
  const setFeedback=(el,type,html)=>{el.className=`feedback show ${type}`;el.innerHTML=html;};
  const clearFeedback=el=>{el.className="feedback";el.innerHTML="";};
  const sameMembers=(a,b)=>{const x=[...a].sort(),y=[...b].sort();return x.length===y.length&&x.every((v,i)=>v===y[i]);};
  const shuffle=a=>{const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]];}return c;};

  function showSection(n){state.section=Number(n);$$('.lesson-section').forEach((s,i)=>s.classList.toggle('active',i===state.section));$$('.nav-step').forEach((b,i)=>b.classList.toggle('active',i===state.section));const labels=['Teach','Prepare','Connect','Measure','Inspect & Listen','Interpret','Close the Loop','Complete'];$('#progressText').textContent=labels[state.section];$('#progressBar').style.width=`${state.section/7*100}%`;requestAnimationFrame(()=>{const sec=$(`.lesson-section[data-section-panel="${state.section}"]`);if(sec){window.scrollTo({top:Math.max(0,sec.getBoundingClientRect().top+window.scrollY-STICKY_HEADER_OFFSET),behavior:'smooth'});}});}

  function selectSingle(container,key,value){$$('.select-option',container).forEach(b=>b.classList.toggle('selected',b.dataset[key]===value));}
  function renderEquipment(){const tray=$('#equipmentTray');tray.innerHTML='';equipment.forEach(([id,label,file])=>{const b=document.createElement('button');b.type='button';b.className='equipment-card';b.dataset.id=id;b.innerHTML=`<img src="${file}" alt="${label}"><strong>${label}</strong>`;b.addEventListener('click',()=>{state.equipment.includes(id)?state.equipment=state.equipment.filter(x=>x!==id):state.equipment.push(id);b.classList.toggle('selected',state.equipment.includes(id));clearFeedback($('#prepareFeedback'));$('#toConnect').disabled=true;});tray.appendChild(b);});}

  function createSortable(container,steps){container.innerHTML='';shuffle(steps).forEach(step=>{const item=document.createElement('div');item.className='sortable-item';item.dataset.step=step;item.innerHTML=`<span class="drag-handle">☰</span><div><div style="display:flex;gap:10px;align-items:center"><span class="order-number"></span><span>${step}</span></div><div class="keyboard-order-controls"><button type="button" class="move-btn up">↑</button><button type="button" class="move-btn down">↓</button></div></div><span class="sort-status"></span>`;item.draggable=true;item.addEventListener('dragstart',()=>item.classList.add('dragging'));item.addEventListener('dragend',()=>{item.classList.remove('dragging');sync(container);});item.addEventListener('dragover',e=>e.preventDefault());item.addEventListener('drop',e=>{e.preventDefault();const d=$('.dragging',container);if(!d||d===item)return;const items=[...container.children],from=items.indexOf(d),to=items.indexOf(item);from<to?item.after(d):item.before(d);sync(container);});$('.up',item).onclick=()=>{const p=item.previousElementSibling;if(p)container.insertBefore(item,p);sync(container);};$('.down',item).onclick=()=>{const n=item.nextElementSibling;if(n)n.after(item);sync(container);};container.appendChild(item);});sync(container);}
  function sync(container){[...container.children].forEach((it,i)=>{$('.order-number',it).textContent=i+1;it.classList.remove('correct-position','wrong-position');$('.sort-status',it).textContent='';});}
  function gradeSortable(container,expected){let c=0;[...container.children].forEach((it,i)=>{const ok=it.dataset.step===expected[i];it.classList.toggle('correct-position',ok);it.classList.toggle('wrong-position',!ok);$('.sort-status',it).textContent=ok?'✓ Correct':'Adjust';if(ok)c++;});return c===expected.length;}

  function renderIds(){const opts=[['name','Full name'],['dob','Date of birth'],['room','Room number'],['diagnosis','Surgical diagnosis']];const wrap=$('#identifierChoices');wrap.innerHTML='';opts.forEach(([id,label])=>{const b=document.createElement('button');b.type='button';b.className='choice-chip';b.textContent=label;b.onclick=()=>{if(state.ids.includes(id))state.ids=state.ids.filter(x=>x!==id);else if(state.ids.length<2)state.ids.push(id);else state.ids=[state.ids[1],id];$$('.choice-chip',wrap).forEach(x=>x.classList.toggle('selected',state.ids.includes(x.dataset.id)));$('#toMeasure').disabled=true;clearFeedback($('#connectFeedback'));};b.dataset.id=id;wrap.appendChild(b);});}
  function renderChoiceStack(id,choices,stateKey,dataKey){const wrap=$(id);wrap.innerHTML='';choices.forEach(([value,text])=>{const b=document.createElement('button');b.type='button';b.className='select-option';b.dataset[dataKey]=value;b.textContent=text;b.onclick=()=>{state[stateKey]=value;selectSingle(wrap,dataKey,value);};wrap.appendChild(b);});}
  function renderInspection(){renderChoiceStack('#inspectionChoices',[["normal","Breathing is regular and unlabored with symmetric chest movement."],["accessory","Accessory muscle use is present despite a normal respiratory rate."],["tripod","The patient is leaning forward in a tripod position."],["retractions","Intercostal retractions are visible during inspiration."]],'inspectionSingle','finding');}
  function renderBreathSounds(){const cards=[['normal','Normal / clear','assets/breath-sounds-normal-card.png'],['wheeze','Wheezes','assets/breath-sounds-wheeze-card.png'],['crackles','Crackles','assets/breath-sounds-crackles-card.png'],['diminished','Diminished','assets/breath-sounds-diminished-card.png']];const wrap=$('#breathSoundChoices');wrap.innerHTML='';cards.forEach(([id,label,file])=>{const b=document.createElement('button');b.type='button';b.className='breath-card';b.dataset.sound=id;b.innerHTML=`<img src="${file}" alt="${label} breath sound teaching card"><strong>${label}</strong>`;b.onclick=()=>{state.breath=id;$$('.breath-card',wrap).forEach(x=>x.classList.toggle('selected',x===b));};wrap.appendChild(b);});}

  $('#startPractice').onclick=()=>showSection(1);
  $('#checkPrepare').onclick=()=>{const expected=equipment.filter(x=>x[3]).map(x=>x[0]);if(sameMembers(state.equipment,expected)){setFeedback($('#prepareFeedback'),'correct','<strong>Correct.</strong> These tools support observation, measurement, auscultation, and documentation. Treatment or diagnostic equipment is not indicated simply because it is available.');$('#toConnect').disabled=false;}else{setFeedback($('#prepareFeedback'),'incorrect','<strong>Adjust the tray.</strong> Bring the tools needed for a routine bedside respiratory assessment. Do not add treatment or invasive diagnostic equipment unless the order or patient condition calls for it.');$('#toConnect').disabled=true;}};
  $('#resetPrepare').onclick=()=>{state.equipment=[];renderEquipment();clearFeedback($('#prepareFeedback'));$('#toConnect').disabled=true;};
  $('#toConnect').onclick=()=>showSection(2);
  $('#checkConnect').onclick=()=>{const seq=gradeSortable($('#connectSequence'),connectExpected),ids=sameMembers(state.ids,['name','dob']);if(seq&&ids){setFeedback($('#connectFeedback'),'correct','<strong>Correct.</strong> You entered safely, identified the patient with two valid identifiers, explained the assessment, and positioned the patient for a reliable respiratory exam.');$('#toMeasure').disabled=false;}else{setFeedback($('#connectFeedback'),'incorrect',`<strong>Keep working.</strong> ${!seq?'Check the opening sequence. ':''}${!ids?'Use two person-specific identifiers; room number and diagnosis are not acceptable identifiers.':''}`);$('#toMeasure').disabled=true;}};
  $('#toMeasure').onclick=()=>showSection(3);
  $('#checkMeasure').onclick=()=>{if(state.measure==='quiet'&&state.ox==='verify'){setFeedback($('#measureFeedback'),'correct','<strong>Correct.</strong> Observe respirations without prompting the patient to consciously change breathing, and trust pulse oximetry only after correct placement and a believable signal.');$('#toInspect').disabled=false;}else{setFeedback($('#measureFeedback'),'incorrect','<strong>Not quite.</strong> Avoid announcing that you are counting respirations. For SpO₂, correct placement alone is not enough—you also need a believable signal/readout.');$('#toInspect').disabled=true;}};
  $('#toInspect').onclick=()=>showSection(4);
  $('#checkInspect').onclick=()=>{if(state.inspectionSingle==='normal'&&state.breath==='normal'){setFeedback($('#inspectFeedback'),'correct','<strong>Correct.</strong> The visual assessment and bilateral breath sounds agree with the stable vital signs. A systematic side-to-side pattern reduces the chance of missing a region.');$('#toInterpret').disabled=false;}else{setFeedback($('#inspectFeedback'),'incorrect','<strong>Reassess the patient.</strong> The case depicts a comfortable postoperative patient without visible increased work of breathing. Match the breath-sound choice to that stable presentation.');$('#toInterpret').disabled=true;}};
  $('#toInterpret').onclick=()=>showSection(5);
  $('#checkInterpret').onclick=()=>{if(state.interpret==='routine'){setFeedback($('#interpretFeedback'),'correct','<strong>Correct.</strong> No immediate respiratory intervention is indicated. Continue routine monitoring and document the findings.');$('#toClose').disabled=false;}else{setFeedback($('#interpretFeedback'),'incorrect','<strong>Look at the whole pattern.</strong> Normal work of breathing, RR 16/min, SpO₂ 97% on room air, and clear bilateral breath sounds do not support immediate respiratory treatment or escalation.');$('#toClose').disabled=true;}};
  $('#toClose').onclick=()=>showSection(6);
  $('#checkClose').onclick=()=>{const seq=gradeSortable($('#closeSequence'),closeExpected);if(seq&&state.doc==='best'){setFeedback($('#closeFeedback'),'correct','<strong>Correct.</strong> The encounter is closed completely: patient safety, equipment care, hand hygiene, documentation, and communication are all addressed.');$('#finishPatient').disabled=false;}else{setFeedback($('#closeFeedback'),'incorrect',`<strong>Almost there.</strong> ${!seq?'Adjust the completion sequence. ':''}${state.doc!=='best'?'Choose documentation that records objective findings and oxygen status without adding unsupported conclusions.':''}`);$('#finishPatient').disabled=true;}};
  $('#finishPatient').onclick=()=>showSection(7);
  $('#restartLesson').onclick=()=>location.reload();

  $$('.nav-step').forEach(b=>b.onclick=()=>{const target=Number(b.dataset.section);if(target===0||target<=state.section)showSection(target);});

  renderEquipment();createSortable($('#connectSequence'),connectExpected);createSortable($('#closeSequence'),closeExpected);renderIds();
  renderChoiceStack('#measureTechnique',[["announce","Tell the patient you are counting respirations, then count for 30 seconds."],["quiet","Continue appearing to assess the pulse while quietly observing respiratory rate, rhythm, depth, and effort."],["estimate","Estimate respirations from the monitor because the patient looks comfortable."]],'measure','measure');
  renderChoiceStack('#oxTechnique',[["verify","Place the probe correctly, minimize motion, and verify that the displayed pulse/signal is believable before accepting the SpO₂."],["instant","Apply the probe and document the first number that appears."],["blanket","Place the probe over any convenient finger even if nail coverage or poor perfusion affects the signal."]],'ox','ox');
  renderInspection();renderBreathSounds();
  renderChoiceStack('#interpretChoices',[["routine","No immediate respiratory intervention; document findings and continue routine monitoring."],["oxygen","Start supplemental oxygen because the patient is postoperative."],["neb","Administer a bronchodilator treatment to prevent postoperative bronchospasm."],["abg","Obtain an arterial blood gas to confirm the normal pulse-ox reading."]],'interpret','decision');
  renderChoiceStack('#documentationChoices',[["best","RR 16/min, regular and unlabored; chest movement symmetric; breath sounds clear/equal bilaterally; SpO₂ 97% on room air; no acute respiratory distress observed."],["vague","Respiratory assessment normal. Patient doing fine."],["overstate","Postoperative patient has no pulmonary complications and will not require respiratory therapy."],["omit","SpO₂ 97%. No other documentation needed because findings were normal."]],'doc','doc');
  showSection(0);
  console.info('PulmoLearn Respiratory Routine practice engine v1.0 — Guided Patient 1');
})();
