(() => {
  "use strict";
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const STORAGE_KEY="pulmolearn.oxygenTanks.v3";
  const labels=["Teach","Prepare","Move & Secure","Connect","Check & Calculate","Deliver Gas","Shutdown","Complete"];
  const state={section:0,unlockedThrough:0,scenarioIndex:0,completedScenarios:[],equipment:[],cylinderVerification:null,moveMatches:{},selectedMoveImage:null,connectOrder:[],leakChoice:null,duration:null,supplyDecision:null,flow:null,shutdownOrder:[],doc:null};
  const scenarios=[
    {name:"Scenario 1 · Routine bedside setup",support:"Guided",caseText:"A secured E-cylinder of medical oxygen is needed at the bedside for a patient whose ordered oxygen flow is 2 L/min. The cylinder pressure is 1800 psi and there is no evidence of a leak during setup.",factor:0.28,pressure:1800,flow:2,needMinutes:120,leak:false,decision:"enough",prepareCue:"Select the oxygen cylinder, compatible regulator/reducing valve, portable carrier/cart, cylinder wrench, and sealing washer. The lab reference factor is supplied below.",moveCue:"Keep the cylinder physically secured whenever it is being stored, transported, or placed for use.",connectCue:"Prepare the cylinder outlet before attaching the regulator. Point the valve away from bystanders before cracking the cylinder.",checkCue:"Open the cylinder as listed in the competency, listen for leaks, then calculate how many minutes of oxygen are available.",flowCue:"Set the flowmeter to the ordered 2 L/min.",shutdownCue:"After use, close the valve, bleed pressure from the regulator, turn the flowmeter off, remove the regulator, cap and label the cylinder, and return it appropriately.",completionHeading:"Scenario 1: Routine Setup Established",completionClinical:"You completed the full cylinder routine and confirmed that the available supply was adequate before beginning oxygen delivery.",completionNext:"Scenario 2 introduces an audible leak that must be corrected before use.",doc:`E-cylinder oxygen placed in service at 1800 psi; oxygen flow 2 L/min; calculated duration approximately 252 minutes; no leak detected; cylinder setup completed and beginning pressure/time recorded.`},
    {name:"Scenario 2 · Audible leak during setup",support:"Supported",caseText:"An E-cylinder is prepared for a patient receiving oxygen at 2 L/min. The cylinder pressure is 1500 psi. After the regulator is connected and the valve is opened, you hear an audible hiss at the connection.",factor:0.28,pressure:1500,flow:2,needMinutes:90,leak:true,decision:"enough",prepareCue:"Use the same equipment routine. This time you will also need to respond correctly if the leak check is abnormal.",moveCue:"Do not carry an unsecured cylinder by hand. Use the portable carrier/cart and maintain secure positioning.",connectCue:"Inspect the opening and make sure the regulator is compatible and the sealing washer is in place before tightening.",checkCue:"The leak check is part of the competency. Correct the leak before deciding the cylinder is ready for patient use.",flowCue:"Once the leak is corrected and supply is confirmed, set the ordered 2 L/min.",shutdownCue:"Shut down only after patient use is complete. Bleed regulator pressure before removing the regulator.",completionHeading:"Scenario 2: Leak Response",completionClinical:"You recognized that an audible leak requires closing the valve, bleeding regulator pressure, turning the flowmeter off, retightening, reopening, and reassessing before use.",completionNext:"Scenario 3 requires deciding whether the remaining oxygen will last for the planned transport.",doc:`E-cylinder oxygen checked at 1500 psi for 2 L/min use; audible leak noted at connection, valve closed and regulator pressure bled, connection retightened, valve reopened and leak resolved; calculated duration approximately 210 minutes; beginning pressure/time recorded.`},
    {name:"Scenario 3 · Is there enough oxygen?",support:"Reduced support",caseText:"A patient needs 4 L/min oxygen for a planned 90-minute transport. The available E-cylinder reads 800 psi. There is no audible leak.",factor:0.28,pressure:800,flow:4,needMinutes:90,leak:false,decision:"replace",prepareCue:"Select only the equipment required for safe cylinder transport, setup, and delivery.",moveCue:"Use the same transport sequence without relying on step-by-step hints.",connectCue:"Complete the connection sequence from memory, including the outlet inspection and sealing washer check.",checkCue:"Calculate the available duration and compare it with the entire planned 90-minute transport before accepting this cylinder.",flowCue:"If the supply decision is correct, practice the ordered 4 L/min setting on the replacement-ready setup.",shutdownCue:"Complete the post-use shutdown and return routine in the correct sequence.",completionHeading:"Scenario 3: Supply Before Transport",completionClinical:"The cylinder contained about 56 minutes at 4 L/min, which is not sufficient for a 90-minute transport. The competency requires replacing a cylinder that does not contain enough oxygen.",completionNext:"Scenario 4 removes most support and asks you to complete the full sequence independently.",doc:`E-cylinder checked at 800 psi for planned oxygen flow 4 L/min; calculated duration approximately 56 minutes, insufficient for 90-minute transport; cylinder replaced before transport; beginning pressure/time documented for the cylinder placed in service.`},
    {name:"Scenario 4 · Independent cylinder workflow",support:"Independent",caseText:"You are asked to independently prepare an E-cylinder for 3 L/min oxygen. The cylinder pressure is 1000 psi, the anticipated use is 60 minutes, and the connection is leak-free.",factor:0.28,pressure:1000,flow:3,needMinutes:60,leak:false,decision:"enough",prepareCue:"Complete the equipment selection independently.",moveCue:"Arrange the transport and securing actions from memory.",connectCue:"Complete the outlet preparation and regulator setup independently.",checkCue:"Use the reference factor to calculate duration and decide whether the supply is adequate for the anticipated use.",flowCue:"Set the ordered 3 L/min.",shutdownCue:"Complete the shutdown, regulator removal, cap/label/return, hygiene, and documentation routine independently.",completionHeading:"Scenario 4: Independent Cylinder Competency",completionClinical:"You completed the oxygen-cylinder workflow independently from equipment selection through safe shutdown and documentation.",completionNext:"You are ready to rehearse the L-5 skill in the physical lab using the program competency checklist.",doc:`E-cylinder oxygen placed in service at 1000 psi; oxygen flow 3 L/min; calculated duration approximately 93 minutes, adequate for anticipated 60-minute use; no leak detected; beginning pressure/time documented and cylinder returned/labeled appropriately after use.`}
  ];
  const p=()=>scenarios[state.scenarioIndex];
  const equipment=[
    ["oxygen","Medical oxygen cylinder","assets/oxygen-cylinder.png",true],
    ["regulator","Compatible regulator","assets/regulator.png",true],
    ["cart","Portable cylinder cart","assets/cart.png",true],
    ["wrench","Cylinder wrench","assets/wrench.png",true],
    ["washer","Sealing washer","assets/washer.png",true],
    ["neb","Nebulizer kit","assets/nebulizer.png",false],
    ["syringe","ABG syringe","assets/syringe.png",false],
    ["spirometer","Spirometer","assets/spirometer.png",false]
  ];
  const moveExpected=["Release the storage safety strap or chain when ready to move the cylinder","Move the cylinder onto the portable carrier or cart safely","Secure the cylinder to the portable carrier or cart","Move the cart to the desired location","Perform hand hygiene and appropriate isolation precautions if necessary","Secure the cylinder at the new location if it is removed from the cart"];
  const moveScenes=[
    {id:"release",step:moveExpected[0],src:"assets/transport-release-storage-restraint.png",alt:"Male respiratory therapist releasing the storage restraint from an oxygen cylinder in the hospital cylinder storage area"},
    {id:"load",step:moveExpected[1],src:"assets/transport-load-cylinder-cart.png",alt:"Male respiratory therapist moving an oxygen cylinder onto a portable oxygen cylinder cart"},
    {id:"secure-cart",step:moveExpected[2],src:"assets/transport-secure-cylinder-cart.png",alt:"Male respiratory therapist securing an oxygen cylinder to the portable cart"},
    {id:"hallway",step:moveExpected[3],src:"assets/transport-wheel-cart-hallway.png",alt:"Male respiratory therapist transporting a secured oxygen cylinder cart through a hospital hallway"},
    {id:"hygiene",step:moveExpected[4],src:"assets/transport-hand-hygiene-isolation.png",alt:"Male respiratory therapist performing hand hygiene and preparing for isolation precautions outside a patient room"},
    {id:"secure-room",step:moveExpected[5],src:"assets/transport-secure-cylinder-patient-room-ppe.png",alt:"Male respiratory therapist wearing appropriate PPE while securing an oxygen cylinder at the patient care location"}
  ];
  const connectExpected=["Remove the protective cap or wrap","Inspect the cylinder opening for debris or dirt","Turn the valve away from bystanders and warn that a loud noise may occur","Crack the cylinder by briefly opening and closing the valve with the wrench","Confirm the regulator/reducing valve is compatible and the sealing washer is in place","Make sure the regulator/flow control is off, then tighten the regulator securely","Open the cylinder valve until the pressure-gauge needle stops rising","Turn the valve stem back one-half turn as listed in the competency"];
  const shutdownExpected=["Close the cylinder valve stem using the appropriate wrench","Turn the flowmeter on until gas evacuates the regulator","Turn the flowmeter off","Remove the regulator/reducing valve","Replace the safety cap and label the cylinder appropriately","Return the cylinder to the appropriate storage location","Discard supplies, remove PPE as applicable, and perform hand hygiene"];
  const leakCorrect="close-bleed-retighten";
  const expectedEquipment=equipment.filter(x=>x[3]).map(x=>x[0]);
  const shuffle=a=>{const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]];}return c;};
  const sameMembers=(a,b)=>{const x=[...a].sort(),y=[...b].sort();return x.length===y.length&&x.every((v,i)=>v===y[i]);};
  function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}catch(e){}}
  function load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;const s=JSON.parse(raw);if(s&&typeof s==='object')Object.assign(state,s);state.scenarioIndex=Math.min(Math.max(Number(state.scenarioIndex)||0,0),3);state.section=Math.min(Math.max(Number(state.section)||0,0),7);state.unlockedThrough=Math.max(Number(state.unlockedThrough)||0,state.section);if(!Array.isArray(state.completedScenarios))state.completedScenarios=[];if(!state.moveMatches||typeof state.moveMatches!=='object'||Array.isArray(state.moveMatches))state.moveMatches={};if(typeof state.cylinderVerification!=='string')state.cylinderVerification=null;}catch(e){}}
  function setFeedback(el,type,html){el.className=`feedback show ${type}`;el.innerHTML=html;}function clearFeedback(el){el.className='feedback';el.innerHTML='';}
  function showSection(n){state.section=Number(n);state.unlockedThrough=Math.max(state.unlockedThrough,state.section);save();$$('.lesson-section').forEach((s,i)=>s.classList.toggle('active',i===state.section));$$('.nav-step').forEach((b,i)=>b.classList.toggle('active',i===state.section));$('#progressText').textContent=labels[state.section];$('#progressBar').style.width=`${state.section/7*100}%`;window.scrollTo({top:0,behavior:'smooth'});}
  function clearMarks(root){if(!root)return;$$('.answer-wrong,.answer-correct',root).forEach(x=>x.classList.remove('answer-wrong','answer-correct'));}
  function markSet(rootSel,key,selected,correct){const root=$(rootSel);clearMarks(root);const ss=new Set(selected),cc=new Set(correct);$$(`[data-${key}]`,root).forEach(b=>{const v=b.dataset[key];if(ss.has(v))b.classList.add(cc.has(v)?'answer-correct':'answer-wrong');});}
  function markChoice(rootSel,key,selected,correct){const root=$(rootSel);clearMarks(root);if(!selected)return;const b=$(`[data-${key}="${selected}"]`,root);if(b)b.classList.add(selected===correct?'answer-correct':'answer-wrong');}
  function renderEquipment(){const wrap=$('#equipmentTray');wrap.innerHTML='';shuffle(equipment).forEach(([id,label,img])=>{const b=document.createElement('button');b.type='button';b.className='equipment-card';b.dataset.id=id;b.innerHTML=`<img src="${img}" alt="${label}"><strong>${label}</strong>`;b.classList.toggle('selected',state.equipment.includes(id));b.onclick=()=>{clearMarks(wrap);state.equipment.includes(id)?state.equipment=state.equipment.filter(x=>x!==id):state.equipment.push(id);b.classList.toggle('selected',state.equipment.includes(id));$('#toMove').disabled=true;clearFeedback($('#prepareFeedback'));save();};wrap.appendChild(b);});}
  function renderCylinderVerification(){
    renderChoiceStack('#cylinderVerificationChoices',[
      ['both','Verify the cylinder contents using the cylinder label and the identifying color used by the lab/facility.'],
      ['color','Use cylinder color alone to identify the gas.'],
      ['shape','Identify the gas from cylinder size and valve shape only.']
    ],'cylinderVerification','verify');
  }
  function moveSceneById(id){return moveScenes.find(x=>x.id===id);}
  function moveSceneForStep(step){return moveScenes.find(x=>x.step===step);}
  function placedMoveIds(){return Object.values(state.moveMatches||{}).filter(Boolean);}
  function assignMoveImage(step,id){
    if(!step||!id)return;
    if(!state.moveMatches||typeof state.moveMatches!=='object'||Array.isArray(state.moveMatches))state.moveMatches={};
    Object.keys(state.moveMatches).forEach(k=>{if(state.moveMatches[k]===id)delete state.moveMatches[k];});
    state.moveMatches[step]=id; state.selectedMoveImage=null; clearFeedback($('#moveFeedback')); $('#toConnect').disabled=true; save(); renderMoveMatch();
  }
  function renderMoveMatch(){
    const tray=$('#moveImageTray'), grid=$('#moveSequence'); if(!tray||!grid)return;
    tray.innerHTML=''; grid.innerHTML='';
    const used=new Set(placedMoveIds());
    const available=shuffle(moveScenes.filter(x=>!used.has(x.id)));
    available.forEach(scene=>{
      const b=document.createElement('button'); b.type='button'; b.className='move-scene-card'; b.draggable=true; b.dataset.scene=scene.id; b.setAttribute('aria-pressed',state.selectedMoveImage===scene.id?'true':'false');
      b.classList.toggle('selected',state.selectedMoveImage===scene.id); b.innerHTML=`<img src="${scene.src}" alt="${scene.alt}"><span>Drag or select this scene</span>`;
      b.addEventListener('click',()=>{state.selectedMoveImage=state.selectedMoveImage===scene.id?null:scene.id;save();renderMoveMatch();});
      b.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',scene.id);e.dataTransfer.effectAllowed='move';});
      tray.appendChild(b);
    });
    if(!available.length){const done=document.createElement('p');done.className='move-tray-empty';done.textContent='All scene images have been placed. Check your matches below.';tray.appendChild(done);}
    moveExpected.forEach((step,i)=>{
      const slot=document.createElement('button'); slot.type='button'; slot.className='move-drop-slot'; slot.dataset.step=step; slot.setAttribute('aria-label',`Step ${i+1}: ${step}. Drop or select the matching scene image.`);
      const id=(state.moveMatches||{})[step], scene=moveSceneById(id);
      slot.innerHTML=`<div class="move-drop-image">${scene?`<img src="${scene.src}" alt="${scene.alt}">`:'<span class="move-drop-placeholder">Drop image here</span>'}</div><div class="move-step-caption"><span class="move-step-number">${i+1}</span><span>${step}</span></div>`;
      if(scene)slot.classList.add('filled');
      slot.addEventListener('dragover',e=>{e.preventDefault();slot.classList.add('drag-over');});
      slot.addEventListener('dragleave',()=>slot.classList.remove('drag-over'));
      slot.addEventListener('drop',e=>{e.preventDefault();slot.classList.remove('drag-over');const sid=e.dataTransfer.getData('text/plain');assignMoveImage(step,sid);});
      slot.addEventListener('click',()=>{if(state.selectedMoveImage){assignMoveImage(step,state.selectedMoveImage);}else if(scene){delete state.moveMatches[step];save();renderMoveMatch();clearFeedback($('#moveFeedback'));$('#toConnect').disabled=true;}});
      grid.appendChild(slot);
    });
  }
  function gradeMoveMatch(){
    let ok=true;
    $$('.move-drop-slot',$('#moveSequence')).forEach(slot=>{
      const step=slot.dataset.step, chosen=(state.moveMatches||{})[step], correct=moveSceneForStep(step)?.id;
      slot.classList.remove('answer-correct','answer-wrong');
      if(!chosen){ok=false;return;}
      const good=chosen===correct; ok=ok&&good; slot.classList.add(good?'answer-correct':'answer-wrong');
    });
    return ok;
  }
  function renderSortable(sel,expected,stateKey){const wrap=$(sel);wrap.innerHTML='';let order=state[stateKey];if(!Array.isArray(order)||order.length!==expected.length||!sameMembers(order,expected)){order=shuffle(expected);state[stateKey]=[...order];}order.forEach(step=>{const item=document.createElement('div');item.className='sortable-item';item.draggable=true;item.dataset.step=step;item.innerHTML=`<span class="drag-handle">☰</span><div><div style="display:flex;gap:10px;align-items:center"><span class="order-number"></span><span>${step}</span></div><div class="keyboard-order-controls"><button type="button" class="move-btn up">↑</button><button type="button" class="move-btn down">↓</button></div></div><span class="sort-status"></span>`;item.addEventListener('dragstart',()=>item.classList.add('dragging'));item.addEventListener('dragend',()=>{item.classList.remove('dragging');syncSortable(wrap,stateKey);});item.addEventListener('dragover',e=>e.preventDefault());item.addEventListener('drop',e=>{e.preventDefault();const d=$('.dragging',wrap);if(!d||d===item)return;const items=[...wrap.children],from=items.indexOf(d),to=items.indexOf(item);from<to?item.after(d):item.before(d);syncSortable(wrap,stateKey);});$('.up',item).onclick=()=>{const prev=item.previousElementSibling;if(prev)wrap.insertBefore(item,prev);syncSortable(wrap,stateKey);};$('.down',item).onclick=()=>{const next=item.nextElementSibling;if(next)next.after(item);syncSortable(wrap,stateKey);};wrap.appendChild(item);});syncSortable(wrap,stateKey);}
  function syncSortable(wrap,stateKey){state[stateKey]=[...wrap.children].map(x=>x.dataset.step);[...wrap.children].forEach((it,i)=>{$('.order-number',it).textContent=i+1;it.classList.remove('correct-position','wrong-position');$('.sort-status',it).textContent='';});save();}
  function gradeSortable(sel,expected){const wrap=$(sel);let ok=true;[...wrap.children].forEach((it,i)=>{const good=it.dataset.step===expected[i];ok=ok&&good;it.classList.toggle('correct-position',good);it.classList.toggle('wrong-position',!good);$('.sort-status',it).textContent=good?'✓ Correct':'Adjust';});return ok;}
  function renderChoiceStack(sel,choices,stateKey,dataKey){const wrap=$(sel);wrap.innerHTML='';shuffle(choices).forEach(([v,t])=>{const b=document.createElement('button');b.type='button';b.className='select-option';b.dataset[dataKey]=v;b.textContent=t;b.classList.toggle('selected',state[stateKey]===v);b.onclick=()=>{clearMarks(wrap);state[stateKey]=v;$$('.select-option',wrap).forEach(x=>x.classList.toggle('selected',x===b));save();};wrap.appendChild(b);});}
  function expectedDuration(){return Math.round(p().pressure*p().factor/p().flow);}
  function renderSystem(){const deg=-140+(p().pressure/2000)*280;$('#gaugeNeedle').style.transform=`rotate(${deg}deg)`;$('#gaugePressure').textContent=`${p().pressure} psi`;$('#leakObservation').textContent=p().leak?'Audible hiss heard at connection':'No audible leak detected';$('#leakObservation').classList.toggle('leak',p().leak);$('#leakPanel').hidden=!p().leak;renderChoiceStack('#leakChoices',[["close-bleed-retighten","Close the valve, turn on the flowmeter to bleed regulator pressure, turn the flowmeter off, retighten the connection, reopen the valve, and reassess for leaks."],["tighten-live","Leave the cylinder open and tighten the regulator while it remains pressurized."],["ignore","Continue if the pressure gauge appears stable because a small audible leak is acceptable."],["remove-live","Remove the regulator immediately without first closing the cylinder and bleeding pressure."]],'leakChoice','leak');renderChoiceStack('#supplyDecision',[["enough",`The cylinder contains enough oxygen for the planned ${p().needMinutes}-minute use.`],["replace",`Replace the cylinder because the calculated duration is not enough for the planned ${p().needMinutes}-minute use.`]],'supplyDecision','supply');$('#durationAnswer').value=state.duration??'';}
  function renderFlow(){const s=$('#flowSlider');s.value=state.flow??0;$('#flowValue').textContent=s.value;}
  function renderDoc(){const choices=[["best",p().doc],["vague","Oxygen tank used. Patient received oxygen. No further details documented."],["pressure-only",`Cylinder pressure ${p().pressure} psi. No flow, duration, leak status, or beginning time documented.`],["unsafe","Cylinder was connected and used. Remaining pressure was not checked because oxygen was flowing normally."]];renderChoiceStack('#documentationChoices',choices,'doc','doc');}
  function applyScenario(){const x=p();$$('.patient-badge').forEach(e=>e.textContent=`Scenario ${state.scenarioIndex+1} of 4`);$$('.support-badge').forEach(e=>e.textContent=x.support);$('#scenarioName').textContent=x.name;$('#scenarioCase').textContent=x.caseText;$('#prepareCue').innerHTML=`<strong>${x.support} cue:</strong> ${x.prepareCue}`;$('#referenceCard').textContent=`E-cylinder factor for this practice station: ${x.factor} L/psi · Cylinder pressure: ${x.pressure} psi · Ordered flow: ${x.flow} L/min · Planned use: ${x.needMinutes} min`;$('#moveCue').innerHTML=`<strong>${x.support} cue:</strong> ${x.moveCue}`;$('#connectCue').innerHTML=`<strong>${x.support} cue:</strong> ${x.connectCue}`;$('#checkCue').innerHTML=`<strong>${x.support} cue:</strong> ${x.checkCue}`;$('#flowCue').innerHTML=`<strong>${x.support} cue:</strong> ${x.flowCue}`;$('#shutdownCue').innerHTML=`<strong>${x.support} cue:</strong> ${x.shutdownCue}`;renderEquipment();renderCylinderVerification();renderMoveMatch();renderSortable('#connectSequence',connectExpected,'connectOrder');renderSortable('#shutdownSequence',shutdownExpected,'shutdownOrder');renderSystem();renderFlow();renderDoc();restoreUI();renderCompletion();}
  function restoreUI(){const x=p();$('#toMove').disabled=!(sameMembers(state.equipment,expectedEquipment)&&state.cylinderVerification==='both');$('#toConnect').disabled=!moveExpected.every(step=>(state.moveMatches||{})[step]===moveSceneForStep(step).id);$('#toCheck').disabled=!sameMembers(state.connectOrder,connectExpected);const durationOK=Number(state.duration)===expectedDuration();const leakOK=!x.leak||state.leakChoice===leakCorrect;$('#toDeliver').disabled=!(durationOK&&leakOK&&state.supplyDecision===x.decision);$('#toShutdown').disabled=Number(state.flow)!==x.flow;$('#finishScenario').disabled=!(sameMembers(state.shutdownOrder,shutdownExpected)&&state.doc==='best');}
  function renderCompletion(review=state.scenarioIndex){const q=scenarios[review];$('#completionHeading').textContent=q.completionHeading;$('#completionClinical').textContent=q.completionClinical;$('#completionNext').textContent=q.completionNext;const tabs=$('#completionReviewTabs');tabs.innerHTML='';[...state.completedScenarios].sort((a,b)=>a-b).forEach(i=>{const b=document.createElement('button');b.type='button';b.className='completion-review-tab';b.classList.toggle('active',i===review);b.innerHTML=`<span class="tab-check">✓</span>Scenario ${i+1}`;b.onclick=()=>renderCompletion(i);tabs.appendChild(b);});const next=$('#nextScenario');if(state.scenarioIndex<3){next.style.display='inline-block';next.textContent=`Start Scenario ${state.scenarioIndex+2}`;}else next.style.display='none';}
  function resetScenarioState(){Object.assign(state,{equipment:[],cylinderVerification:null,moveMatches:{},selectedMoveImage:null,connectOrder:[],leakChoice:null,duration:null,supplyDecision:null,flow:null,shutdownOrder:[],doc:null,section:1,unlockedThrough:1});['#prepareFeedback','#moveFeedback','#connectFeedback','#systemFeedback','#flowFeedback','#shutdownFeedback'].forEach(s=>clearFeedback($(s)));save();}

  $('#startPractice').onclick=()=>showSection(1);
  $('#checkPrepare').onclick=()=>{markSet('#equipmentTray','id',state.equipment,expectedEquipment);markChoice('#cylinderVerificationChoices','verify',state.cylinderVerification,'both');const equipOK=sameMembers(state.equipment,expectedEquipment),verifyOK=state.cylinderVerification==='both';if(equipOK&&verifyOK){setFeedback($('#prepareFeedback'),'correct','<strong>Correct.</strong> You selected the oxygen cylinder, compatible regulator, cart, wrench, and sealing washer, and verified cylinder contents using the label and identifying color used by the lab/facility.');$('#toMove').disabled=false;}else{setFeedback($('#prepareFeedback'),'incorrect',`<strong>Adjust the preparation.</strong> ${!equipOK?'Recheck the equipment outlined in red and make sure every required cylinder-handling item is present. ':''}${!verifyOK?'Verify the medical gas using both the cylinder label and the identifying color used by the lab/facility.':''}`);$('#toMove').disabled=true;}save();};
  $('#resetPrepare').onclick=()=>{state.equipment=[];state.cylinderVerification=null;renderEquipment();renderCylinderVerification();clearFeedback($('#prepareFeedback'));$('#toMove').disabled=true;save();};
  $('#toMove').onclick=()=>showSection(2);
  $('#checkMove').onclick=()=>{if(gradeMoveMatch()){setFeedback($('#moveFeedback'),'correct','<strong>Correct.</strong> Each hospital scene matches the competency step it illustrates. The cylinder remains controlled and secured through storage, transport, isolation preparation, and placement at the destination.');$('#toConnect').disabled=false;}else{setFeedback($('#moveFeedback'),'incorrect','<strong>Recheck the scene matches.</strong> Boxes outlined in red contain a scene that does not match the competency text shown at the bottom. Select or drag a different image into those boxes.');$('#toConnect').disabled=true;}save();};
  $('#resetMove').onclick=()=>{state.moveMatches={};state.selectedMoveImage=null;renderMoveMatch();clearFeedback($('#moveFeedback'));$('#toConnect').disabled=true;save();};
  $('#toConnect').onclick=()=>showSection(3);
  $('#checkConnect').onclick=()=>{if(gradeSortable('#connectSequence',connectExpected)){setFeedback($('#connectFeedback'),'correct','<strong>Correct.</strong> You prepared the outlet, warned bystanders, cracked the cylinder, verified compatibility and the sealing washer, tightened the regulator with flow off, then opened the valve as listed in the competency.');$('#toCheck').disabled=false;}else{setFeedback($('#connectFeedback'),'incorrect','<strong>Recheck the connection sequence.</strong> Correct the rows marked “Adjust” before pressurizing the regulator.');$('#toCheck').disabled=true;}save();};
  $('#toCheck').onclick=()=>showSection(4);
  $('#durationAnswer').addEventListener('input',()=>{state.duration=Number($('#durationAnswer').value);save();});
  $('#checkSystem').onclick=()=>{state.duration=Number($('#durationAnswer').value);const durationOK=state.duration===expectedDuration(),leakOK=!p().leak||state.leakChoice===leakCorrect,decisionOK=state.supplyDecision===p().decision;if(p().leak)markChoice('#leakChoices','leak',state.leakChoice,leakCorrect);markChoice('#supplyDecision','supply',state.supplyDecision,p().decision);if(durationOK&&leakOK&&decisionOK){setFeedback($('#systemFeedback'),'correct',`<strong>Correct.</strong> Duration = ${p().pressure} × ${p().factor} ÷ ${p().flow} ≈ <strong>${expectedDuration()} minutes</strong>. ${p().decision==='replace'?'That is not enough for the planned use, so the cylinder should be replaced before proceeding.':'The available supply is adequate for the planned use.'}${p().leak?' You also corrected the leak before using the cylinder.':''}`);$('#toDeliver').disabled=false;}else{const parts=[];if(!durationOK)parts.push('recalculate the duration using pressure × factor ÷ flow');if(!leakOK)parts.push('correct the audible leak by closing the valve, bleeding regulator pressure, turning the flowmeter off, retightening, reopening, and reassessing');if(!decisionOK)parts.push('compare your calculated minutes with the entire planned use');setFeedback($('#systemFeedback'),'incorrect',`<strong>Keep working.</strong> ${parts.join('; ')}.`);$('#toDeliver').disabled=true;}save();};
  $('#toDeliver').onclick=()=>showSection(5);
  $('#flowSlider').addEventListener('input',()=>{$('#flowValue').textContent=$('#flowSlider').value;});
  $('#setFlow').onclick=()=>{state.flow=Number($('#flowSlider').value);if(state.flow===p().flow){setFeedback($('#flowFeedback'),'correct',`<strong>Correct.</strong> Flowmeter set to ${p().flow} L/min.`);$('#toShutdown').disabled=false;}else{setFeedback($('#flowFeedback'),'incorrect',`<strong>Adjust the flowmeter.</strong> The ordered flow for this scenario is ${p().flow} L/min.`);$('#toShutdown').disabled=true;}save();};
  $('#toShutdown').onclick=()=>showSection(6);
  $('#checkShutdown').onclick=()=>{const seq=gradeSortable('#shutdownSequence',shutdownExpected);markChoice('#documentationChoices','doc',state.doc,'best');if(seq&&state.doc==='best'){setFeedback($('#shutdownFeedback'),'correct','<strong>Correct.</strong> You shut down the cylinder, bled regulator pressure, removed the regulator, capped/labeled/returned the cylinder, completed hygiene, and documented the beginning pressure and use.');$('#finishScenario').disabled=false;}else{setFeedback($('#shutdownFeedback'),'incorrect',`<strong>Close the loop completely.</strong> ${!seq?'Correct the shutdown rows marked “Adjust.” ':''}${state.doc!=='best'?'Choose documentation that includes the beginning pressure and clinically relevant cylinder-use details.':''}`);$('#finishScenario').disabled=true;}save();};
  $('#finishScenario').onclick=()=>{if(!state.completedScenarios.includes(state.scenarioIndex))state.completedScenarios.push(state.scenarioIndex);save();renderCompletion();showSection(7);};
  $('#nextScenario').onclick=()=>{if(state.scenarioIndex>=3)return;state.scenarioIndex++;resetScenarioState();applyScenario();showSection(1);};
  $('#restartLesson').onclick=()=>{localStorage.removeItem(STORAGE_KEY);Object.assign(state,{section:0,unlockedThrough:0,scenarioIndex:0,completedScenarios:[],equipment:[],cylinderVerification:null,moveMatches:{},selectedMoveImage:null,connectOrder:[],leakChoice:null,duration:null,supplyDecision:null,flow:null,shutdownOrder:[],doc:null});applyScenario();showSection(0);};
  $$('.nav-step').forEach((b,i)=>b.onclick=()=>{if(i<=state.unlockedThrough||i===0||state.completedScenarios.length)showSection(i);});
  load();applyScenario();showSection(state.section);
})();
